<?php
// A default config file for the usual laravel & lumen folders
return [
    'cache' => false,
    'rules' => [
        '@PSR2' => true,
        '@DoctrineAnnotation' => true,
        'align_multiline_comment' => true,
        'array_indentation' => true,
        'array_syntax' => ['syntax' => 'short'],
        'binary_operator_spaces' => [
            'operators' => [
                '=>'  => null,
                '='   => 'single_space',
                '*'   => 'single_space',
                '/'   => 'single_space',
                '%'   => 'single_space',
                '<'   => 'single_space',
                '>'   => 'single_space',
                '|'   => 'single_space',
                '^'   => 'single_space',
                '+'   => 'single_space',
                '-'   => 'single_space',
                '&'   => 'single_space',
                '&='  => 'single_space',
                '&&'  => 'single_space',
                '||'  => 'single_space',
                '.='  => 'single_space',
                '/='  => 'single_space',
                '=='  => 'single_space',
                '>='  => 'single_space',
                '===' => 'single_space',
                '!='  => 'single_space',
                '<>'  => 'single_space',
                '!==' => 'single_space',
                '<='  => 'single_space',
                'and' => 'single_space',
                'or'  => 'single_space',
                'xor' => 'single_space',
                '-='  => 'single_space',
                '%='  => 'single_space',
                '*='  => 'single_space',
                '|='  => 'single_space',
                '+='  => 'single_space',
                '<<'  => 'single_space',
                '<<=' => 'single_space',
                '>>'  => 'single_space',
                '>>=' => 'single_space',
                '^='  => 'single_space',
                '**'  => 'single_space',
                '**=' => 'single_space',
                '<=>' => 'single_space',
                '??'  => 'single_space',
                '??=' => 'single_space',
            ],
        ],
        'cast_spaces' => ['space' => 'single'],
        'concat_space' => ['spacing' => 'one'],
        'constant_case' => true,
        'elseif' => true,
        'function_typehint_space' => true,
        'encoding' => true,
        'lowercase_keywords' => true,
        'method_chaining_indentation' => true,
        'no_short_bool_cast' => true,
        'no_trailing_comma_in_singleline' => true,
        'no_unneeded_curly_braces' => true,
        'no_unused_imports' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'no_spaces_around_offset' => ['positions' => ['inside', 'outside']],
        'no_whitespace_in_blank_line' => true,
        'no_whitespace_before_comma_in_array' => true,
        'normalize_index_brace' => true,
        'not_operator_with_successor_space' => true,
        'ordered_imports' => ['sort_algorithm' => 'alpha'],
        'operator_linebreak' => true,
        'php_unit_method_casing' => true,
        'phpdoc_trim' => true,
        'return_type_declaration' => ['space_before' => 'none'],
        'simplified_if_return' => true,
        'single_quote' => true,
        'single_blank_line_at_eof' => true,
        'standardize_not_equals' => true,
        'switch_case_semicolon_to_colon' => true,
        'switch_continue_to_break' => true,
        'ternary_to_null_coalescing' => true,
        'trailing_comma_in_multiline' => ['elements' => ['arrays']],
        'trim_array_spaces' => true,
        'whitespace_after_comma_in_array' => true,
    ],
    'finder' => [
        'include'  => [],
        'exclude'  => ['bootstrap', 'vendor', 'storage'],
        'name'     => ['*.php'],
        'notname'  => ['*.blade.php'],
        // This assumes this file is in your_app/vendor/comlaude/php-formatter/config/php-formatter.php
        // so it points to your_app/
        'in'       => __DIR__ . '/../../../../',
    ],
];
